### PR TITLE
YouTube Home Page Clone project

### PR DESCRIPTION
**Pull request by aecordova**
Please review code... team:@lucasmazo32  and @aecordova

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi Lucila!  
### Your project looks :+1:  
#### Readme file should be descriptive. You can use this article [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
#### Kindly recommended check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
screen1

Please follow this instruction building project [Embedding Images and Video](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/)

#### Navigation bar
It has an embedded image that represents a logo.
The logo is aligned to the leftmost part of the navbar.
It has an input tag that represents a search bar.
The search bar is aligned to the middle of the navbar.
It has a button tag that represents the search button.
The search button is at the end (rightmost part) of the search bar.
It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.

#### Video
It is displayed.
It shows the video title.
It shows the number of views.
It has like and dislike icons.
It has a share button.
It shows the avatar of the user who uploaded the video.
It has a subscribe button.

#### Sidebar Recommended videos
It shows the recommended video’s thumbnail preview.
It shows the title of the video.
It shows the number of views.


Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *




#### But your project needs some Required Changes

**Comment by aecordova** [comment]
Submitted requested changes @Anna-Myzukina

**Comment by shshamim63** [comment]
## Status :tada: !!Approved!! :tada: 
___
Hi @aecordova and @lucasmazo32 :wave: ,
Awesome job :clap: . You have gathered all the part that is needed to decorate the page. And the items are placed on the correct position. There are some spaces that you should cover before merging it.
___
### :spades: [Mandatory Changes] :spades: 
___
I can see some commented code on your stylebck.css file. Please remove them. 
https://github.com/lucasmazo32/youtube-homepage/blob/7fbe51e14e9ed6450a5ae5e8e93fa5a3c979345b/stylebck.css#L32-L53
___
### :spades: [Optional Changes] :spades: 
1. there are multiple css files in your project. I think that if your create a folder called style and place all your css file in it. that will be better organized. To make it more organized, you can generate an assets folder which will contain image, style folder. So if anyone want to look at your repository, after separation of file it will make easy access.
2. You can make your readme more professional. Maybe by answering some questions, like->
...1. What is this project about?
...2. What are the tools that you have used?
...3. Who are the contributors and how to contact with them?
...4. Is there any live demo? and so on...
___
#### After fixing the changes you can merge this project. This :+1:  is from me in advance. Best of luck for your new project. And don't forget to fill the project completion form
___
## :herb: Happy Coding :herb:
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Pull request merged**
